networks:
  web:
    driver: bridge
  internal:
    driver: bridge

volumes:
  pgdata:

services:
  db:
    image: postgres:16
    container_name: pg
    restart: unless-stopped
    env_file: .env
    environment:
      POSTGRES_DB: ${DB_NAME_PROD}
      POSTGRES_USER: ${DB_USER_PROD}
      POSTGRES_PASSWORD: ${DB_PASSWORD_PROD}
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    networks:
      - internal
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER_PROD} -d ${DB_NAME_PROD}"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: node-app
    restart: unless-stopped
    env_file: .env
    environment:
      DATABASE_URL: postgres://${DB_USER_PROD}:${DB_PASSWORD_PROD}@db:5432/${DB_NAME_PROD}
      NODE_ENV: prod  
      PORT: 3000
    depends_on:
      db:
        condition: service_healthy
    expose:
      - "3000"
    networks:
      - internal

  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      app:
        condition: service_started
    networks:
      - web
      - internal